language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

jdk:
- oraclejdk8

script:
- ./gradlew clean build

after_success:
- .buildscript/deploy_snapshot.sh

env:
  matrix:
    - MODULE=arraysetbackport
  global:
    - secure: "VqSa+m/kuExKtD2KK+knVbxkWxuKtPMFf5zbGzsQkvTxlW35h1pgDR+edYwdpnmyYS2nhfoQ23+RPxYR6CGZiy02Q7eRwh8u8xojqPnrgOwxwM/yTtUz12XH7A+2V74fxWFgiBGG12yHtg2UTA0978x/J3CY0GyXFYWeC3GucPBXoCpFKtS4jCj67ennAiEjoJDG3zl+96o2iJP72DfeWDruHoBRHAJrd+Wehepv5+hFAn2yNwqTyio099uAEacxwa4R9x1rW0Av9mQDVXNL3xlMTVEB+eZ24PYAD9eDtr1C16szKaE6z+k/nBs9LbWIfYROzrezPINUxs01Vp5TqqQGdK+du6HS4BhRVfj9Wo+dS/ovpyu9yTCEeKbngtEn56KRvHzXywcTfbrlJsLtTrcPBLdFXXuim51Jf+dd10l0gAJZdUNLpgUO8oslrKn9k6X8wr7lmsEjwM3N2xbtzBW8RQhTx2eU/dK2kD34mFzjepi6IuZORa1UHp/a+x8xzNkJx6fPEQiz7xI9CrGj7/3s6Einw51jt1yBGlP5hnmfWbHsexMucbUuDA6JuEdDmRcQWFNJ7Egb8AmJOxn3TDk11094VUrJuW8kOopSoeelHrxdoSFVQaUkgKNyJ6EW0ZXUSSZzSeZphOO4lefPL3YF8WnLU0+rYIa7r5FSd28="
    - secure: "EJ1trlXvdHEAN+BCPfpktJOAijPOpYrFb0VvdjhPRFbDEjGH1S4TXR1JF0ESgZSyhvzbHPgSNF40Ra+FJ8GOfJUZD/rgOXhNjDhy6dEDOBuxx986exzNk+T+gBE4RNiSzxiPR+Rtm/myyvWckhmTqkuSNWwowmFA0zdxovN5iIkNfJ6aZxYF5TkPYUDTgjb+NhC3cUe4qES2Zex+1rkAEGaQ9ABF9rGBCiTO+nmfeI5KsRk+RBTPV3HkvAMiV4iv91PdgD7mz+8GgsItLsRvEf7HS8g9lVtIROX/nDep0ozyNlG9PoIjWiK0jP43xKqy595XLU5HvC+QzZuNicgL2iQOurxluyxmDkDSdB4dEiYSnqUbzoJ5kAvbDlcmDxKVfSFgGACUYPqk9RgyZVrkQUMVm0DlWmM6JRMlkEEDKA2kEUimibCL9wPCrDDQj4FYbSYESh9dplvbLo8SQ3YioabnofJdJ0a8R+7BJuIy8MTdRKHXY7HsRe+Tc/tt75Rl/sRGHwBSIvpXqque2TBwuz999DVQWUPBTBOmWsVWjvaHTFkH0cVV57CthoWIcDyw/TS5zrz4jexXIfX1B1dsyGt+cKZ4KYGg+XBVBQMEfElDoQK16pzBv5NnhVmoxSVqG4CSO/tvQKADeFGuZI0hzP97pvb5hBaL/TbyQ3LwwpY="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - "$HOME/.gradle"
